openapi: 3.0.3
info:
  title: Conference Room Booking System API
  description: |
    **Primary Developer**: Siphosenkosi
    **Project**: BitCube Professional Training - Module 4.3
    **Purpose**: This is the formal contract for the Conference Room Booking System. It defines all endpoints for managing rooms, bookings, and availability.
  version: 1.0.0
  contact:
    name: Siphosenkosi
    email: siphosenkosi@bitcube.ac.za

servers:
  - url: http://localhost:3000/v1
    description: Local development server
  - url: https://api.staging.bitcube.ac.za/v1
    description: Staging environment for testing
  - url: https://api.bitcube.ac.za/v1
    description: Production environment

paths:
  # ========== ROOMS ENDPOINTS (3) ==========
  /rooms:
    get:
      summary: List all available rooms
      description: Retrieves a list of all active conference rooms. Can be filtered.
      security:
        - BearerAuth: []
      parameters:
        - name: minCapacity
          in: query
          required: false
          schema:
            type: integer
          description: Filter by minimum room capacity
        - name: hasProjector
          in: query
          required: false
          schema:
            type: boolean
          description: Filter rooms that have a projector
      responses:
        '200':
          description: Successfully retrieved room list
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Room'
                  timestamp:
                    type: string
                    format: date-time
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

    post:
      summary: Create a new room (Admin)
      description: Adds a new conference room to the system. Requires admin privileges.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoomCreate'
      responses:
        '201':
          description: Room created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  data:
                    $ref: '#/components/schemas/Room'
                  message:
                    type: string
                    example: "Room created successfully"
                  timestamp:
                    type: string
                    format: date-time
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '403':
          description: Forbidden - Admin access required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /rooms/{id}:
    get:
      summary: Get a specific room
      description: Retrieves detailed information for a single room by its ID.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 101
          description: The unique ID of the room
      responses:
        '200':
          description: Room details retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  data:
                    $ref: '#/components/schemas/Room'
                  timestamp:
                    type: string
                    format: date-time
        '404':
          description: Room not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  # ========== BOOKINGS ENDPOINTS (4) ==========
  /bookings:
    get:
      summary: List all bookings
      description: Retrieves bookings, optionally filtered by user or room.
      security:
        - BearerAuth: []
      parameters:
        - name: userId
          in: query
          required: false
          schema:
            type: string
          description: Filter bookings by user ID
        - name: roomId
          in: query
          required: false
          schema:
            type: integer
          description: Filter bookings by room ID
      responses:
        '200':
          description: List of bookings retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Booking'
                  timestamp:
                    type: string
                    format: date-time
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

    post:
      summary: Create a new booking
      description: Books a conference room for a specific time period.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingCreate'
      responses:
        '201':
          description: Booking created successfully
          headers:
            Location:
              description: URL of the new booking
              schema:
                type: string
                example: "/bookings/5001"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  data:
                    $ref: '#/components/schemas/Booking'
                  message:
                    type: string
                    example: "Booking created successfully"
                  timestamp:
                    type: string
                    format: date-time
        '400':
          description: Invalid data or time in the past
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '409':
          description: Conflict - Room already booked for that time
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '404':
          description: Room not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /bookings/{id}:
    get:
      summary: Get a specific booking
      description: Retrieves details for a single booking by its ID.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 5001
          description: The booking ID
      responses:
        '200':
          description: Booking details retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  data:
                    $ref: '#/components/schemas/Booking'
                  timestamp:
                    type: string
                    format: date-time
        '404':
          description: Booking not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

    delete:
      summary: Cancel a booking
      description: Cancels an existing booking. Users can only cancel their own bookings.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 5001
          description: The booking ID
      responses:
        '204':
          description: Booking successfully cancelled (no content)
        '403':
          description: Forbidden - Cannot cancel another user's booking
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '404':
          description: Booking not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  # ========== AVAILABILITY ENDPOINTS (2) ==========
  /availability:
    get:
      summary: Check room availability
      description: Finds rooms available for a given time period.
      security:
        - BearerAuth: []
      parameters:
        - name: startTime
          in: query
          required: false
          schema:
            type: string
            format: date-time
            example: "2026-01-22T10:00:00Z"
          description: Start of the desired time slot (ISO format)
        - name: endTime
          in: query
          required: false
          schema:
            type: string
            format: date-time
            example: "2026-01-22T11:00:00Z"
          description: End of the desired time slot (ISO format)
        - name: minCapacity
          in: query
          required: false
          schema:
            type: integer
          description: Filter for rooms with minimum capacity
      responses:
        '200':
          description: List of available rooms for the slot
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        isAvailable:
                          type: boolean
                        availableSlots:
                          type: array
                          items:
                            type: object
                            properties:
                              startTime:
                                type: string
                                format: date-time
                              endTime:
                                type: string
                                format: date-time
                  timestamp:
                    type: string
                    format: date-time
        '400':
          description: Invalid time parameters (e.g., end before start)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /availability/rooms/{id}:
    get:
      summary: Check availability for a specific room
      description: Checks if a specific room is available for a given time period.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 101
          description: The room ID to check
        - name: startTime
          in: query
          required: false
          schema:
            type: string
            format: date-time
            example: "2026-01-22T10:00:00Z"
        - name: endTime
          in: query
          required: false
          schema:
            type: string
            format: date-time
            example: "2026-01-22T11:00:00Z"
      responses:
        '200':
          description: Availability status retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  data:
                    type: object
                    properties:
                      isAvailable:
                        type: boolean
                        example: true
                      conflictingBooking:
                        $ref: '#/components/schemas/Booking'
                  timestamp:
                    type: string
                    format: date-time
        '404':
          description: Room not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

components:
  schemas:
    # === REUSABLE SCHEMAS ===
    Room:
      type: object
      required:
        - id
        - name
        - capacity
        - isActive
      properties:
        id:
          type: integer
          example: 101
          description: Unique room identifier
        name:
          type: string
          example: "Boardroom Alpha"
        capacity:
          type: integer
          example: 12
          description: Maximum number of occupants
        isActive:
          type: boolean
          example: true
          description: Whether the room can be booked
        hasProjector:
          type: boolean
          example: true
        hasWhiteboard:
          type: boolean
          example: true
        location:
          type: string
          example: "Floor 5, North Wing"
        hourlyRate:
          type: number
          format: float
          example: 50.0
        amenities:
          type: array
          items:
            type: string
          example: ["Projector", "Whiteboard", "Video Conference"]

    RoomCreate:
      type: object
      required:
        - name
        - capacity
      properties:
        name:
          type: string
          example: "Innovation Lab"
        capacity:
          type: integer
          example: 20
        hasProjector:
          type: boolean
          example: true
        hasWhiteboard:
          type: boolean
          example: true
        location:
          type: string
          example: "Floor 6, Innovation Wing"
        hourlyRate:
          type: number
          format: float
          example: 75.0

    Booking:
      type: object
      required:
        - id
        - roomId
        - userId
        - title
        - startTime
        - endTime
        - status
      properties:
        id:
          type: integer
          example: 5001
        roomId:
          type: integer
          example: 101
        userId:
          type: string
          example: "user_abc123"
        title:
          type: string
          example: "Team Stand-up"
        startTime:
          type: string
          format: date-time
          example: "2026-01-22T10:00:00Z"
        endTime:
          type: string
          format: date-time
          example: "2026-01-22T11:00:00Z"
        status:
          type: string
          enum: [CONFIRMED, CANCELLED]
          example: "CONFIRMED"
        createdAt:
          type: string
          format: date-time
          example: "2026-01-21T14:30:00Z"
        notes:
          type: string
          example: "Daily team synchronization meeting"

    BookingCreate:
      type: object
      required:
        - roomId
        - title
        - startTime
        - endTime
      properties:
        roomId:
          type: integer
          example: 101
        userId:
          type: string
          example: "user_abc123"
        title:
          type: string
          example: "Team Stand-up"
        startTime:
          type: string
          format: date-time
          example: "2026-01-22T10:00:00Z"
        endTime:
          type: string
          format: date-time
          example: "2026-01-22T11:00:00Z"
        notes:
          type: string
          example: "Need projector for presentation"

    ApiError:
      type: object
      properties:
        status:
          type: string
          example: "error"
        errorCode:
          type: string
          example: "ROOM_NOT_FOUND"
        message:
          type: string
          example: "The requested resource was not found."
        details:
          type: string
          example: "Room with ID 999 does not exist in the database."
        timestamp:
          type: string
          format: date-time
          example: "2026-01-22T14:30:00Z"

  # === AUTHENTICATION DEFINITION ===
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: >
        Enter your JWT token in the format: `Bearer <token>`
        Example: `Bearer eyJhbGciOiJIUzI1NiIs...`

  # === SECURITY REQUIREMENTS ===
security:
  - BearerAuth: []